vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
        circle_logo:
            uri_prefix: /images/circles
            upload_destination: '%kernel.project_dir%/public/images/circles'
        material_image:
            uri_prefix: /images/materials
            upload_destination: '%kernel.project_dir%/public/images/materials'
